[package]
name = "zfs-touch-from-snap"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
common = { path = "../common" }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
glob = { version = "0.3" }
filetime = "0.2"
