[package]
name = "zfs-snap"
version = "2.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.3", features = ["derive"] }
common = { path = "../common" }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
