[package]
name = "zfs-snap"
version = "2.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
common = { path = "../common" }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
